language: python
python: 2.7
branches:
  only:
  - master
  - v0.2.0-dev
env:
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=pypy
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=manifest
before_install:
- pip install codecov
install:
- pip install tox
script:
- tox --hashseed 0 -e $TOX_ENV
after_success:
- codecov
notifications:
  email: false
  irc: "chat.freenode.net#ramlfications"
  slack:
    secure: TWn+jseoa8McZptuY7Zr/2AkrWKd9tSmvCoCszYkGHyHp+PAdnxH96Wxweq4pL1A1QoMtsgYM5dhPEPUfV9xCRN1FU6OMPtchMjgC740vqNsLE0+cjz6We3COw9+BHoLk7Nh2SgAzjxS9X+0Bv6tDBf1CvA7SIyM1ssLQifnX+M=
deploy:
  provider: pypi
  user: roguelynn
  password:
    secure: XgUz7PiCHCOVM1yZeNfuy2j73aAGpW5HtTocmjlKNqG9wKXGkqV4IFWneznE1n8hqQj+Tqmm4MQ0AftJcomEh9WESVsglwMOqwMericRcsVkrEq+XHPynMfqsUc/MEr+zAB/Tj9SsbYMjP8zsk4TdJx/s+EbYFXsDfHrxcQY6q4=
  on:
    tags: true
  distributions: sdist bdist_wheel
